version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    commit-message:
      prefix: "WIP [Prod]"
      prefix-development: "[Dev]"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    commit-message:
      prefix: "[Dev]"
