name: Annotate NPM Dependencies
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  annotate-npm-dependencies:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
    uses: pangaeatech/.github/.github/workflows/annotate-npm-dependencies.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      branch: ${{ github.head_ref }}
