name: Annotate NPM Dependencies
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  annotate-npm-dependencies:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    uses: pangaeatech/.github/.github/workflows/annotate-npm-dependencies.yml@main
    with:
      pr_url: ${{github.event.pull_request.html_url}}
      branch: ${{github.head_ref}}
