name: Automatically Create PR and Add to Redmine on New Branches
concurrency: auto-pr-${{ github.ref }}
on:
  push:
    branches-ignore:
      - $default-branch
      - "dependabot/**"
      - "renovate/**"
      - "whitesource/**"
      # Add any other branches you want to ignore

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_url: ${{ steps.open-pr.outputs.pr_url }}
      pr_num: ${{ steps.open-pr.outputs.pr_number }}
      pr_created: ${{ steps.open-pr.outputs.pr_created }}
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          pr_title: "${{ github.ref_name }}"
          pr_label: "auto-pr"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: $default-branch

  extractnum:
    needs: pull-request
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.extract.outputs.replaced }}
    steps:
      - id: extract
        uses: frabert/replace-string-action@v2
        with:
          pattern: "^(task|issue|bug)(\\d+)-.*$"
          flags: "i"
          string: "${{ github.ref_name }}"
          replace-with: "$2"

  link-to-redmine:
    needs: [extractnum, pull-request]
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' && needs.extractnum.outputs.issue != github.ref_name }}
    uses: pangaeatech/.github/.github/workflows/link-to-redmine.yml@main
    with:
      pr_num: ${{ needs.pull-request.outputs.pr_num }}
      pr_url: ${{ needs.pull-request.outputs.pr_url }}
      rm_issue: ${{ needs.extractnum.outputs.issue }}
      rm_url: "https://redmine.mycompany.com" # Set to your URL
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-to-redmine:
    needs: [extractnum, pull-request]
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' && needs.extractnum.outputs.issue == github.ref_name }}
    uses: pangaeatech/.github/.github/workflows/add-to-redmine.yml@main
    with:
      pr_num: ${{ needs.pull-request.outputs.pr_num }}
      pr_url: ${{ needs.pull-request.outputs.pr_url }}
      pr_subject: ${{ github.ref_name }}
      rm_url: "https://redmine.mycompany.com" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
      rm_tracker_id: 13 # Set to your tracker id (optional)
      rm_version_id: 10 # Set to your version id (optional)
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}
