name: Enable Auto-Squash-and-Merge for Development Dependencies
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  enable-auto-merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: ${{ steps.metadata.outputs.dependency-type == 'direct:development' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
