name: Link to Redmine Issue Based on Branch Name
on:
  pull_request:
    types: [opened, reopened]
    branches: [$default-branch]

permissions:
  contents: read
  pull-requests: write

jobs:
  extractnum:
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.extract.outputs.replaced }}
    steps:
      - uses: frabert/replace-string-action@v2.0
        id: extract
        with:
          pattern: "^(task|issue|bug)(\\d+)-.*$"
          flags: "i"
          string: "${{ github.head_ref }}"
          replace-with: "$2"

  link-to-redmine:
    needs: extractnum
    if: ${{ needs.extractnum.outputs.issue != github.head_ref }}
    uses: pangaeatech/.github/.github/workflows/link-to-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      pr_url: ${{github.event.pull_request.html_url}}
      rm_issue: ${{ needs.extractnum.outputs.issue }}
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}
