name: NPM Audit

on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm audit --production # OR: yarn audit --groups dependencies,optionalDependencies
        working-directory: ./ # Set to your working directory
