name: NPM Audit

on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm audit --production # OR: yarn audit --groups dependencies,optionalDependencies
        working-directory: ./ # Set to your working directory
