name: Add PR Comments, Reviews and Status to Redmine
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed, reopened, converted_to_draft, ready_for_review, review_requested, edited]

permissions:
  contents: read

jobs:
  add-comment:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    uses: pangaeatech/.github/.github/workflows/update-redmine.yml@main
    with:
      pr_num: ${{github.event.issue.number}}
      cmt_url: ${{github.event.comment.html_url}}
      cmt_user: ${{github.event.comment.user.login}}
      cmt_action: "Commented on the PR:"
      cmt_body: ${{github.event.comment.body}}
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-review-comment:
    if: ${{ github.event_name == 'pull_request_review_comment' }}
    uses: pangaeatech/.github/.github/workflows/update-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      cmt_url: ${{github.event.comment.html_url}}
      cmt_user: ${{github.event.comment.user.login}}
      cmt_action: "Added a Review Comment to the PR:"
      cmt_body: ${{github.event.comment.body}}
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-review:
    if: ${{ github.event_name == 'pull_request_review' }}
    uses: pangaeatech/.github/.github/workflows/update-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      cmt_url: ${{github.event.review.html_url}}
      cmt_user: ${{github.event.review.user.login}}
      cmt_action: "Reviewed the PR as: **${{github.event.review.state}}**"
      cmt_body: ${{github.event.review.body}}
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-status:
    if: ${{ github.event_name == 'pull_request' && (github.event.action != 'closed' || !github.event.pull_request.merged) && github.event.action != 'edited' }}
    uses: pangaeatech/.github/.github/workflows/update-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      cmt_url: ${{github.event.pull_request.html_url}}
      cmt_user: ${{github.event.sender.login}}
      cmt_action: "Set the PR to: **${{github.event.action}}**"
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-merged:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}
    uses: pangaeatech/.github/.github/workflows/update-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      cmt_url: ${{github.event.pull_request.html_url}}
      cmt_user: ${{github.event.sender.login}}
      cmt_action: "Set the PR to: **merged**"
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  update-issue:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'edited' && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'mend-bolt-for-github[bot]') }}
    uses: pangaeatech/.github/.github/workflows/edit-redmine.yml@main
    with:
      pr_num: ${{github.event.pull_request.number}}
      pr_url: ${{github.event.pull_request.html_url}}
      pr_subject: ${{github.event.pull_request.title}}
      pr_body: ${{github.event.pull_request.body}}
      rm_url: "https://redmine.mycompany.com/" # Set to your URL
      rm_project_id: "projectid" # Set to your project id
      rm_field_id: 11 # Set to your field id
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}
