name: Automatically Create PR on New Branches
concurrency: auto-pr-${{ github.ref }}
on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
      - "renovate/**"
      - "whitesource/**"

permissions:
  contents: read
  pull-requests: write
  checks: read
  statuses: read
  repository-projects: read

  # shouldn't need more...
  actions: read

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: gh pr view || gh pr create -d -B "main" -t "${{ github.ref_name }}" -b ""
        env:
          GH_TOKEN: ${{ github.token }}
