# Links an existing issue in Redmine to the specified pull request.
#
# Example Usage:
# --------------
# name: My favorite workflow
# on:
#   pull_request:
#     types: [opened]
# jobs:
#   extractnum:
#     runs-on: ubuntu-latest
#       outputs:
#         issue: ${{ steps.extract.outputs.replaced }}
#       steps:
#         - id: extract
#           uses: frabert/replace-string-action@v2.0
#           with:
#             pattern: "^(task|issue|bug)(\\d+)-.*$"
#             flags: "i"
#             string: "${{ github.head_ref }}"
#             replace-with: "$2"
#
#   link-to-redmine:
#     needs: extractnum
#     if: ${{ needs.extractnum.outputs.issue != github.head_ref }}
#     permissions:
#       contents: read
#       pull-requests: write
#     uses: pangaeatech/.github/.github/workflows/link-to-redmine.yml@main
#     with:
#       pr_num: ${{github.event.pull_request.number}}
#       pr_url: ${{github.event.pull_request.html_url}}
#       rm_url: "https://redmine.mycompany.com/"
#       rm_issue: ${{ needs.extractnum.outputs.issue }}
#       rm_field_id: 11
#     secrets:
#       rm_key: ${{ secrets.REDMINE_API_KEY }}

name: Link To Redmine
on:
  workflow_call:
    inputs:
      pr_num:
        # The Pull Request Number
        required: true
        type: string
      pr_url:
        # The Pull Request URL
        required: true
        type: string
      rm_url:
        # The Redmine URL
        required: true
        type: string
      rm_issue:
        # The redmine issue to link to
        required: true
        type: string
      rm_field_id:
        # The redmine custom field ID to store the PR number in
        required: true
        type: number
    secrets:
      rm_key:
        # The REST API Key of the redmine user to post as
        # NOTE: This user MUST have permission to "Edit issues" and also
        #       to "Add notes" on the project specified by rm_project_id
        required: true
jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - name: Link task to redmine
        run: |
          sudo apt-get install -y jq curl
          BODY=$(echo "Linked to \"Pull Request $PR_NUM\":$PR_URL")
          jq --null-input \
             --arg key "$RM_KEY" \
             --arg body "$BODY" \
             --arg prnum "$PR_NUM" \
             --arg fld "$RM_FIELD_ID" \
             '{key:$key,issue:{notes:$body,custom_fields:[{value:$prnum,id:$fld}]}}' > body.json
          curl -s -X PUT -H "Content-Type: application/json" -d "@body.json" "${RM_URL}/issues/${RM_ISSUE}.json"
          gh pr comment "$PR_URL" -b "Linked to [Redmine Task ${RM_ISSUE}]($RM_URL/issues/${RM_ISSUE})";
        env:
          PR_URL: ${{ inputs.pr_url }}
          PR_NUM: ${{ inputs.pr_num }}
          RM_ISSUE: ${{ inputs.rm_issue }}
          RM_FIELD_ID: ${{ inputs.rm_field_id }}
          RM_URL: ${{ inputs.rm_url }}
          RM_KEY: ${{ secrets.rm_key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
